spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ssdemo?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: sme.narola@gmail.com
    password: km9b`8Z#1@)>ab7
    protocol: smtp
    tls: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 864000000

demo:
    mail:
      baseUrl: http://localhost:8082/

server:
  port: 8082

#otp.simulation: true OTP will be send to mobile
#otp.simulation: false get OTP from log
#otp.validity.time: in minutes
#otp.attempt: how many times user can enter wrong otp
#otp.block.time: time limit in minutes after wrong attempts
otp:
  length: 4
  simulation: true
  validity.time: 1
  attempt: 3
  block.time: 120

#set true to send OTP from Nexmo
sms.sender:
  nexmo: true

sms.provider:
  nexmo:
    api.key: d771f0ff
    api.secret: QOcT1StX1u5t0MrJ